package errors

func ProcessError(err error) []byte {
	return []byte(`just a test`)
}
